backend:
  name: github
  repo: Brunogarcia03/revista-borges
  branch: master
  auth_scope: repo

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "src/content/articulos"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Subtítulo", name: "subtitulo", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Categoría", name: "categoria", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
